### ISSUE TITLE
Activated module crashes checkout page

### ISSUE THREAD

**Issue by AykutCevik** [ratepay/magento2-module#2]
After enabling the RatePAY module I'm not able to proceed to the cart checkout page `/checkout/cart/`.
Error:
```
1 exception(s):
Exception #0 (BadMethodCallException): Missing required argument $text of Magento\Framework\Phrase.

Exception #0 (BadMethodCallException): Missing required argument $text of Magento\Framework\Phrase.
#0 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Framewo...', Array, Array)
#1 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#2 /vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#3 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(144): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#4 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'phrase', 'Magento\\Framewo...')
#5 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Framewo...', Array, Array)
#6 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#7 /vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#8 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(144): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#9 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'paymentExceptio...', 'RatePAY\\Payment...')
#10 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('RatePAY\\Payment...', Array, Array)
#11 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('RatePAY\\Payment...', Array, Array)
#12 /vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('RatePAY\\Payment...')
#13 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(144): Magento\Framework\ObjectManager\ObjectManager->get('RatePAY\\Payment...')
#14 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'RatePAY\\Payment...', NULL, 'rpValidator', 'RatePAY\\Payment...')
#15 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('RatePAY\\Payment...', Array, Array)
#16 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('RatePAY\\Payment...', Array, Array)
#17 /vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('RatePAY\\Payment...', Array)
#18 /vendor/magento/module-payment/Model/Method/Factory.php(40): Magento\Framework\ObjectManager\ObjectManager->create('RatePAY\\Payment...', Array)
#19 /vendor/magento/module-payment/Helper/Data.php(114): Magento\Payment\Model\Method\Factory->create('RatePAY\\Payment...')
#20 /app/code/RatePAY/Payment/Model/RechnungConfigProvider.php(32): Magento\Payment\Helper\Data->getMethodInstance('ratepay_invoice')
#21 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): RatePAY\Payment\Model\RechnungConfigProvider->__construct(Object(Magento\Payment\Helper\Data), Object(Magento\Framework\Escaper))
#22 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('RatePAY\\Payment...', Array)
#23 /vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('RatePAY\\Payment...')
#24 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(180): Magento\Framework\ObjectManager\ObjectManager->get('RatePAY\\Payment...')
#25 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(156): Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray(Array)
#26 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, NULL, NULL, 'configProviders', 'Magento\\Checkou...')
#27 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Checkou...', Array, Array)
#28 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Checkou...', Array, Array)
#29 /vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Checkou...')
#30 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(144): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Checkou...')
#31 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Checkou...', NULL, 'configProvider', 'Magento\\Checkou...')
#32 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Checkou...', Array, Array)
#33 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Checkou...', Array, Array)
#34 /vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Checkou...', Array)
#35 /vendor/magento/framework/View/Element/BlockFactory.php(45): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Checkou...', Array)
#36 /vendor/magento/framework/View/Layout/Generator/Block.php(269): Magento\Framework\View\Element\BlockFactory->createBlock('Magento\\Checkou...', Array)
#37 /vendor/magento/framework/View/Layout/Generator/Block.php(249): Magento\Framework\View\Layout\Generator\Block->getBlockInstance('Magento\\Checkou...', Array)
#38 /vendor/magento/framework/View/Layout/Generator/Block.php(227): Magento\Framework\View\Layout\Generator\Block->createBlock('Magento\\Checkou...', 'checkout.cart.s...', Array)
#39 /vendor/magento/framework/View/Layout/Generator/Block.php(135): Magento\Framework\View\Layout\Generator\Block->generateBlock(Object(Magento\Framework\View\Layout\ScheduledStructure), Object(Magento\Framework\View\Layout\Data\Structure), 'checkout.cart.s...')
#40 /vendor/magento/framework/View/Layout/GeneratorPool.php(80): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#41 /vendor/magento/framework/View/Layout.php(344): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#42 /generated/code/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#43 /vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#44 /vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#45 /vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#46 /vendor/magento/framework/View/Page/Config.php(197): Magento\Framework\View\Layout\Builder->build()
#47 /vendor/magento/framework/View/Page/Config.php(217): Magento\Framework\View\Page\Config->build()
#48 /vendor/magento/module-checkout/Controller/Cart/Index.php(55): Magento\Framework\View\Page\Config->getTitle()
#49 /generated/code/Magento/Checkout/Controller/Cart/Index/Interceptor.php(24): Magento\Checkout\Controller\Cart\Index->execute()
#50 /vendor/magento/framework/App/Action/Action.php(107): Magento\Checkout\Controller\Cart\Index\Interceptor->execute()
#51 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#52 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Controller\Cart\Index\Interceptor->___callParent('dispatch', Array)
#53 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Controller\Cart\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#54 /generated/code/Magento/Checkout/Controller/Cart/Index/Interceptor.php(39): Magento\Checkout\Controller\Cart\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#55 /vendor/magento/framework/App/FrontController.php(55): Magento\Checkout\Controller\Cart\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#56 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#57 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#58 /vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#59 /vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#60 /vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#61 /vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#62 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#63 /generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#64 /vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#65 /vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#66 /pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#67 {main}
```

Is there anything we need to configure first?

Our setup:
Magento 2.2.5
PHP 7.1
MySQL 5.7

**Comment by rpWhittington** [comment]
Hello Aykut,

Thank you for reporting this issue and helping us to improve our software! 

We're looking into the problem and will get back to you as soon as we have more information.

Best regards,

Aaron

**Comment by domeglic** [comment]
I have the same problem and it seems like an easy fix:

`\RatePAY\Payment\Helper\Validator` has a constructor dependency `\Magento\Framework\Exception\PaymentException` that has a required parameter `Phrase` which is 
empty.  
Exceptions are usually just created with `new \Magento\Framework\Exception\PaymentException()` but if the plan is to use this approach then use `\Magento\Framework\Exception\PaymentExceptionFactory` instead.

**Comment by FatchipRobert** [comment]
The problem was fixed in the referenced commit.
